version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Interface web Jaeger
      - "4317:4317"    # Port OpenTelemetry (OTLP)
      - "6831:6831/udp" # Port Thrift (non utilisé ici)